"""Ensure is_sale_recorded in Order

Revision ID: 30a4208e3c74
Revises: 5a40fc49e826
Create Date: 2025-05-07 13:32:59.437007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a4208e3c74'
down_revision = '5a40fc49e826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sale_recorded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_sale_recorded')

    # ### end Alembic commands ###
