"""Initial migration

Revision ID: 78492e73bf8f
Revises: d9abf70b542c
Create Date: 2025-04-22 21:21:07.066992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78492e73bf8f'
down_revision = 'd9abf70b542c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bird_type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('feed_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('low', 'medium', 'high', name='prioritylevel'), nullable=True))

    with op.batch_alter_table('poultry_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('low', 'medium', 'high', name='prioritylevel'), nullable=True))

    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('administered_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Enum('low', 'medium', 'high', name='prioritylevel'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('administered_by')
        batch_op.drop_column('dosage')

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('poultry_batch', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('location')
        batch_op.drop_column('breed')

    with op.batch_alter_table('feed_log', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('bird_type')

    # ### end Alembic commands ###
